export enum EOrderStatus {
    SEARCHING = "SEARCHING",
    ON_MANAGER = "ON_MANAGER",
    WAITING = "WAITING",
    IN_PROGRESS = "IN_PROGRESS",
    CANCELED = "CANCELED",
    REQUIRES_PAYMENT = "REQUIRES_PAYMENT",
    DONE = "DONE"
}