export enum EResponseStatus {
	WAITING = "WAITING",
	IN_PATH = "IN_PATH",
	AWAITING_CONFIRMATION_ARRIVAL = "AWAITING_CONFIRMATION_ARRIVAL",
	IN_PROGRESS = "IN_PROGRESS",
	AWAITING_CONFIRMATION_COMPLETION = "AWAITING_CONFIRMATION_COMPLETION",
	BANNED = "BANNED",
	DONE = "DONE",
}